/**
 * 创建侧边栏使您能够:
 - 创建一个有序的文档组
 - 为该组的每个文档呈现一个侧边栏
 - 提供下/以前的导航

 侧栏可以从文件系统生成，也可以在这里显式定义.

 创建尽可能多的侧边栏.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 默认情况下，Docusaurus会从docs文件夹结构中生成一个侧边栏
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // 但是您可以手动创建侧边栏
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
